#ifndef ENUMS_HPP
#define ENUMS_HPP

enum CONDITION {
	NO_ERROR = 0,
	ERROR = -1
};

enum WARNING_MESSAGE {
	OK_BUTTON = 1,
	CLOSE_BUTTON = 2
};

enum LEN_NUM {
	MIN_LOGIN_CHARACTERS = 7,
	MAX_LOGIN_CHARACTERS = 20,
	MIN_PASSWORD_CHARACTERS = 10,
	MAX_PASSWORD_CHARACTERS = 25
};

enum RECORD {
	MAX_KEEPER_NAME_LEN = 35,
	MAX_LOGIN_LEN = 20,
	MAX_EMAIL_LEN = 30,
	MAX_PASSWORD_LEN = 25
};

#endif