#ifndef ENUMS_HPP
#define ENUMS_HPP

enum CONDITION {
	NO_ERROR = 0,
	ERROR = -1
};

enum LEN_NUM {
	MIN_LOGIN_CHARACTERS = 7,
	MAX_LOGIN_CHARACTERS = 20,
	MIN_PASSWORD_CHARACTERS = 10,
	MAX_PASSWORD_CHARACTERS = 25
};

#endif